languageCode = "en-us"
title = "Don't Follow Me!"
baseurl = "http://localhost:1313/"
theme = "casper"
Copyright = "All rights reserved - 2017"
canonifyurls = true

[params]
	description = "Occasionally Useful"
  	cover = "images/cover.jpg"
  	author = "Leonardo Souza"
  	authorlocation = "Passau, Germany"
  	authorwebsite = "http://leo.org"
  	# logo = "images/me.jpg"
  
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  # githubName = "vjeantet"
  # twitterName = "vjeantet"
  # facebookName = ""
  # linkedinName = ""
 	
 	hideHUGOSupport = false

[[menu.main]]
 	name = "Home"
  	weight = -120
  	identifier = "blog"
  	url = "/"

[[menu.main]]
	name = "Github repos"
	pre = "<h3>Social</h3>"
	url = "https://github.com/leonardossz"
	weight = 100

[[menu.main]]
	name = "Twitter timeline"
	url = "https://twitter.com/f10ck3"
	weight = 101
